In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
conf_filepath = '../simple_env_conf.csv'
site_conf = pd.read_csv(conf_filepath)
site_conf

    #siteid  nodeid   lon   lat  height  azimuth  beamwidth  txpower  gain
0         1       0  1266  2733      30        0         60       43     0
1         1       1  1266  2733      30      120         60       43     0
2         1       2  1266  2733      30      240         60       43     0
3         2       3  1733  3200      30        0         60       43     0
4         2       4  1733  3200      30      120         60       43     0
5         2       5  1733  3200      30      240         60       43     0
6         3       6  1600  2500      30        0         60       43     0
7         3       7  1600  2500      30      120         60       43     0
8         3       8  1600  2500      30      240         60       43     0
9         4       9   700  4266      30        0         60       43     0
10        4      10   700  4266      30      120         60       43     0
11        4      11   700  4266      30      240         60       43     0
12        5      12  2766  3766      30        0         60       43     0
13        5      13  2766  3766      30      120         60       43     0
14        5      14  2766  3766      30      240         60       43     0
15        6      15  1133   666      30        0         60       43     0
16        6      16  1133   666      30      120         60       43     0
17        6      17  1133   666      30      240         60       43     0
18        7      18  2500  2000      30        0         60       43     0
19        7      19  2500  2000      30      120         60       43     0
20        7      20  2500  2000      30      240         60       43     0

In [9]:
filename = '/Volumes/ws/bake/source/ns-3.26/scratch/lena-simple_env.rem'
rem = pd.read_csv(filename, sep='\t', header=None)
# rem.head()
plt.figure(figsize=(9,8))
plt.scatter(rem.loc[:,0], rem.loc[:,1], c = 10*np.log(rem.loc[:,3]), marker='s', edgecolors='none')
plt.colorbar()
plt.show()

RuntimeError: No mappable was found to use for colorbar creation. First define a mappable such as an image (with imshow) or a contour set (with contourf).